"use client"

import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import type { ReactNode } from "react"
import {
  Video,
  Mail,
  Calendar,
  ChevronDown,
  Zap,
  ArrowUp,
  FileDown,
  Activity,
  BadgeCheck,
  Brain,
  CircleDot,
  ShieldAlert,
  Target,
} from "lucide-react"
import { cn } from "@/lib/utils"
import type { ApiIncident, LoadStatus, MemoryMatch } from "@/types/kairo"
import type { AgentReasoning, AgentRuntimeResponse, ChatInteractionIntent } from "@/types/agent"

/** First assistant message that looks like the structured incident brief (LLM, demo, or channel update). */
function findIncidentBriefText(messages: Message[]): string | null {
  for (const m of messages) {
    if (m.role !== "assistant") continue
    if (m.analysis) return m.content
    const c = m.content
    if (/Kairo request failed/i.test(c)) continue
    const hasBoundary = /BOUNDARY|FAULT BOUNDARY/i.test(c)
    const hasBody =
      /RESOLUTION_STEPS|RESOLUTION RUNBOOK|ROOT_CAUSE|ROOT_CAUSE_MEMORY|DIAGNOSIS|LIKELY_CAUSE/i.test(c)
    const channelStyle =
      hasBoundary &&
      /OWNER:|ACTION:|STATUS:/i.test(c)
    const skipRunbook =
      /SKIP_FIRST/i.test(c) && /EXECUTE_NEXT/i.test(c)
    if ((hasBoundary && hasBody) || channelStyle || skipRunbook) return c
  }
  return null
}

function buildPostMortemMarkdown({
  activeIncident,
  analysis,
  memoryMatches,
  fallbackBody,
}: {
  activeIncident: ApiIncident | null
  analysis: AgentReasoning | null | undefined
  memoryMatches: MemoryMatch[]
  fallbackBody: string
}) {
  const generated = new Date().toLocaleString(undefined, {
    dateStyle: "full",
    timeStyle: "short",
  })
  const title = activeIncident?.title ?? "Kairo incident report"
  const vendor = activeIncident?.vendor ?? "Unknown vendor"
  const service = activeIncident?.service ?? "Unknown service"
  const severity = activeIncident?.severity ?? "Unknown severity"
  const impact = activeIncident?.customer_impact ?? activeIncident?.description ?? "Impact summary not recorded."
  const topAction = analysis?.recommended_next_actions?.[0] ?? "Action plan not recorded."
  const rootCause = analysis?.likely_cause ?? "Likely root cause not recorded."
  const checks = analysis?.checks_to_skip?.length ? analysis.checks_to_skip : ["No skipped checks recorded."]
  const references = memoryMatches.length
    ? memoryMatches.map((match) => {
        const meta = match.metadata ?? {}
        return `- ${match.title ?? meta.title ?? match.id} (${match.vendor ?? meta.vendor ?? "unknown"}, ${
          typeof match.similarity === "number" ? `${formatEvidenceStrength(match.similarity)} evidence` : "memory match"
        })`
      })
    : ["- No memory references captured."]

  return `# ${title}

**Generated:** ${generated}  
**Vendor / service:** ${vendor} / ${service}  
**Severity:** ${severity}  
**Status:** Draft postmortem generated by Kairo

## Impact Summary

${impact}

## Incident Timeline

- Incident triggered from Kairo simulation or selected dashboard row.
- Episodic memory retrieval completed against canonical incident memory.
- Kairo generated a structured response using retrieved evidence.
- Operator resolved or prepared to resolve using the recommended response.

## Memory References Used

${references.join("\n")}

## Likely Root Cause

${rootCause}

## Actions Taken / Recommended

${analysis?.recommended_next_actions?.map((action) => `- ${action}`).join("\n") ?? `- ${topAction}`}

## Checks Skipped

${checks.map((check) => `- ${check}`).join("\n")}

## Final Resolution

${topAction}

## Follow-Up / Prevention Notes

- Track recurrence of the same vendor, symptom, region, and failure-mode pattern.
- Keep the retained resolution available for future memory recall.
- Review skipped checks before escalating internal infrastructure work.

## Kairo Reasoning Snapshot

${analysis?.diagnosis ?? fallbackBody.trim()}
`
}

interface Message {
  id: string
  role: "user" | "assistant"
  content: string
  analysis?: AgentReasoning
  intent?: ChatInteractionIntent
  stages?: AgentRuntimeResponse["stages"]
}

const suggestionCards = [
  {
    icon: Video,
    text: "Is this our system or Razorpay?",
  },
  {
    icon: Mail,
    text: "What should I skip checking?",
  },
  {
    icon: Calendar,
    text: "Draft an incident channel update",
  },
]

interface AgentChatProps {
  activeIncident: ApiIncident | null
  injectedMessage: Message | null
  memoryMatches?: MemoryMatch[]
  agentAnalysis?: AgentReasoning | null
  reasoningStatus: LoadStatus
  agentStages: AgentRuntimeResponse["stages"]
  threadKey: number
}

export function AgentChat({
  activeIncident,
  injectedMessage,
  memoryMatches = [],
  agentAnalysis,
  reasoningStatus,
  agentStages,
  threadKey,
}: AgentChatProps) {
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState("")
  const [isSending, setIsSending] = useState(false)
  const bottomRef = useRef<HTMLDivElement | null>(null)

  useEffect(() => {
    setMessages([])
  }, [threadKey])

  useEffect(() => {
    if (!injectedMessage) return

    setMessages((previous) => {
      if (previous.some((message) => message.id === injectedMessage.id)) return previous
      return [...previous, injectedMessage]
    })
  }, [injectedMessage])

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth", block: "end" })
  }, [messages])

  const incidentBriefForExport = useMemo(
    () => findIncidentBriefText(messages),
    [messages]
  )

  const handleExportPostMortem = useCallback(() => {
    if (!incidentBriefForExport) return
    const md = buildPostMortemMarkdown({
      activeIncident,
      analysis: agentAnalysis,
      memoryMatches,
      fallbackBody: incidentBriefForExport,
    })
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" })
    const url = URL.createObjectURL(blob)
    const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19)
    const a = document.createElement("a")
    a.href = url
    a.download = `kairo-incident-report-${ts}.md`
    a.rel = "noopener"
    document.body.appendChild(a)
    a.click()
    a.remove()
    URL.revokeObjectURL(url)
  }, [activeIncident, agentAnalysis, incidentBriefForExport, memoryMatches])

  const handleSend = async () => {
    if (!input.trim()) return
    const userInput = input
    const userMessage: Message = {
      id: Date.now().toString(),
      role: "user",
      content: userInput,
    }

    const nextMessages: Message[] = [...messages, userMessage]
    setMessages(nextMessages)
    setInput("")
    setIsSending(true)

    try {
      const historyPayload = nextMessages.map(({ role, content }) => ({
        role,
        content,
      }))

      const response = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: historyPayload,
          message: userInput,
          currentIncident: activeIncident,
          // Forward the retrieved memory matches so follow-up chats stay grounded
          past_episodes: memoryMatches.length > 0 ? memoryMatches : undefined,
        }),
      })
      const payload = await response.json()

      if (!response.ok || !payload.success) {
        throw new Error(payload.error ?? "analysis failed")
      }
      const data = payload.data

      const assistantMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: data.response,
        analysis: data.analysis ?? undefined,
        intent: data.intent,
        stages: data.stages ?? [],
      }
      setMessages((prev) => [...prev, assistantMessage])
    } catch (error) {
      const message = error instanceof Error ? error.message : "analysis failed"
      setMessages((prev) => [
        ...prev,
        {
          id: (Date.now() + 1).toString(),
          role: "assistant",
          content: `Kairo request failed: ${message}`,
        },
      ])
    } finally {
      setIsSending(false)
    }
  }

  const handleSuggestionClick = (text: string) => {
    setInput(text)
  }

  return (
    <div className="flex h-full flex-col bg-white font-sans antialiased">
      {/* Header */}
      <div className="border-b border-gray-100 bg-[#FAFAFA] px-7 py-5">
        <div className="flex items-center justify-between gap-3">
          <div className="flex min-w-0 flex-1 items-center gap-3">
            <img src="/icon.svg" alt="Kairo Icon" className="h-8 w-8 shrink-0 object-contain" />
            <div className="min-w-0">
              <h3 className="text-[20px] font-bold leading-tight tracking-tight text-gray-900">
                Kairo Agent
              </h3>
              <p className="text-[13px] leading-5 text-gray-500">memory copilot</p>
            </div>
          </div>
          <div
            className="h-2 w-2 shrink-0 rounded-full bg-teal-600 shadow-[0_0_0_4px_rgba(13,148,136,0.12)]"
            aria-hidden
          />
        </div>
        {messages.length > 0 && (
          <div className="mt-4 flex justify-stretch sm:justify-end">
            <button
              type="button"
              onClick={handleExportPostMortem}
              disabled={!incidentBriefForExport}
              title={
                incidentBriefForExport
                  ? "Download post-mortem as Markdown"
                  : "Run an incident brief first (e.g. ask about boundary / resolution)"
              }
              className={cn(
                "group inline-flex w-full items-center justify-center gap-2 rounded-lg border border-gray-100 bg-white px-3 py-2.5 sm:w-auto sm:min-w-[10.5rem]",
                "text-[13px] font-semibold tracking-[-0.01em] text-gray-900 shadow-sm",
                "transition-all duration-200",
                "hover:border-teal-200 hover:bg-teal-50 hover:shadow-md",
                "active:scale-[0.99]",
                "disabled:pointer-events-none disabled:border-gray-100 disabled:bg-gray-50 disabled:text-gray-400 disabled:opacity-45 disabled:shadow-none"
              )}
            >
              <FileDown className="h-3.5 w-3.5 text-gray-500" strokeWidth={2} aria-hidden />
              <span>Export Postmortem</span>
              <FileDown
                className="hidden h-3.5 w-3.5 text-gray-400 transition-colors group-hover:text-teal-600 group-disabled:group-hover:text-gray-400"
                strokeWidth={2}
                aria-hidden
              />
            </button>
          </div>
        )}
      </div>

      {/* Chat Area */}
      <div className="flex-1 overflow-y-auto">
        {messages.length === 0 ? (
          <div className="flex h-full flex-col items-center justify-center px-4">
            {/* Empty State Icon */}
            <div className="mb-6">
              <img src="/kairo-logo.png" alt="Kairo" className="w-36 h-auto object-contain" />
            </div>

            <p className="mb-8 max-w-[280px] text-center text-[15px] leading-6 text-gray-500">
              {reasoningStatus === "loading"
                ? "Analyzing retrieved incident memory..."
                : reasoningStatus === "error"
                  ? "analysis failed; simulate again or select another incident."
                  : "Query incident history, vendor patterns, and memory logs."}
            </p>

            {/* Metrics Row */}
            <div className="mb-8 flex items-center justify-center gap-1.5 text-[12px] text-[#6b7280]">
              <span>{memoryMatches.length} memories</span>
              <span>&middot;</span>
              <span>{activeIncident ? "active incident" : "idle"}</span>
              <span>&middot;</span>
              <span>{agentAnalysis?.referenced_memory_incidents.length ?? 0} refs</span>
            </div>

            <p className="mb-4 text-[13px] text-gray-500">Today&apos;s suggested prompts</p>

            {/* Suggestion Cards */}
            <div className="flex flex-col gap-3 w-full px-3">
              {suggestionCards.map((card, index) => {
                const Icon = card.icon
                return (
                  <button
                    key={index}
                    onClick={() => handleSuggestionClick(card.text)}
                    className="flex items-start gap-3 rounded-lg border border-gray-100 bg-white p-5 text-left transition-all hover:bg-gray-50 hover:border-gray-200 hover:shadow-sm"
                  >
                    <Icon className="mt-0.5 h-4 w-4 shrink-0 text-gray-400" strokeWidth={1.5} />
                    <span className="text-[15px] leading-6 text-gray-900">{card.text}</span>
                  </button>
                )
              })}
            </div>
          </div>
        ) : (
          <div className="flex flex-col gap-5 px-7 py-6">
            {(agentStages.length > 0 || messages.some((message) => message.analysis)) && (
              <ReasoningStages
                status={reasoningStatus === "idle" ? "loaded" : reasoningStatus}
                stages={agentStages.length ? agentStages : latestMessageStages(messages)}
              />
            )}
            {messages.map((message) => (
              <div
                key={message.id}
                className={cn(
                  "flex flex-col",
                  message.role === "user" ? "items-end" : "items-start"
                )}
              >
                {message.role === "assistant" && (
                  <div className="mb-1.5 flex flex-wrap items-center gap-2">
                    <span className="text-[12px] font-semibold text-teal-600">Kairo</span>
                    {message.analysis && (
                      <span className="inline-flex items-center rounded-full border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-emerald-800">
                        Memory Active
                      </span>
                    )}
                  </div>
                )}
                {message.role === "assistant" && message.analysis && (
                  <StructuredReasoning analysis={message.analysis} memoryMatches={memoryMatches} />
                )}
                {!message.analysis && (
                  <div
                    className={cn(
                      "whitespace-pre-wrap px-5 py-4 text-[15px] leading-7 shadow-sm",
                      message.role === "user"
                        ? "max-w-[82%] rounded-[18px_18px_4px_18px] border border-gray-800 bg-gray-900 text-white"
                        : "w-full rounded-lg border border-gray-100 bg-white text-gray-900"
                    )}
                  >
                    {message.content}
                  </div>
                )}
              </div>
            ))}
            <div ref={bottomRef} />
          </div>
        )}
      </div>

      {/* Input Area */}
      <div className="border-t border-gray-100 bg-white p-5">
        {/* Model Selector */}
        <div className="mb-4 flex items-center">
          <button className="flex items-center gap-1.5 text-[13px] text-gray-500 hover:text-gray-900">
            <Zap className="h-3.5 w-3.5" />
            <span>Groq · qwen3</span>
            <ChevronDown className="h-3 w-3" />
          </button>
        </div>
        
        <div className="flex items-center gap-3 border border-[#e5e7eb] rounded-lg bg-gray-100 px-4 py-3 transition-all focus-within:border-gray-300 focus-within:bg-white">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleSend()}
            placeholder="Describe the incident or ask Kairo..."
            className="flex-1 bg-transparent text-[15px] leading-6 text-gray-900 placeholder:text-gray-400 focus:outline-none"
          />
          <button
            onClick={handleSend}
            disabled={isSending}
            className="flex h-8 w-8 items-center justify-center rounded-full bg-gray-900 text-white transition-all duration-200 hover:bg-gray-800 hover:scale-105 disabled:cursor-not-allowed disabled:opacity-60 disabled:hover:scale-100"
          >
            <ArrowUp className="h-4 w-4" strokeWidth={2} />
          </button>
        </div>
      </div>
    </div>
  )
}

function ReasoningStages({
  status,
  stages,
}: {
  status: LoadStatus
  stages: AgentRuntimeResponse["stages"]
}) {
  const stageLabels = [
    "incident normalized",
    "memory recalled",
    "evidence matched",
    "likely cause inferred",
    "action plan generated",
  ]
  const completedCount =
    status === "loaded" ? stageLabels.length : status === "loading" ? 2 : stages.length

  return (
    <div className="rounded-xl border border-gray-100 bg-[#FAFAFA] p-4">
      <div className="mb-4 flex items-center justify-between">
        <span className="text-[12px] font-bold uppercase tracking-[0.12em] text-gray-400">
          Reasoning pipeline
        </span>
        <span className="text-[12px] font-semibold text-gray-500">{status}</span>
      </div>
      <div className="flex flex-wrap gap-1.5">
        {stageLabels.map((label, index) => {
          const done = index < completedCount
          return (
            <span
              key={label}
              className={cn(
                "inline-flex items-center gap-1 rounded-full border px-2.5 py-1.5 text-[12px] font-semibold",
                done
                  ? "border-teal-100 bg-teal-50 text-teal-700"
                  : "border-gray-100 bg-white text-gray-400"
              )}
            >
              <CircleDot className="h-2.5 w-2.5" />
              {label}
            </span>
          )
        })}
      </div>
    </div>
  )
}

function latestMessageStages(messages: Message[]) {
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const stages = messages[index].stages
    if (stages?.length) return stages
  }
  return []
}

function StructuredReasoning({
  analysis,
  memoryMatches,
}: {
  analysis: AgentReasoning
  memoryMatches: MemoryMatch[]
}) {
  const evidenceStrength = analysis.referenced_memory_incidents[0]?.similarity
  const evidence = analysis.referenced_memory_incidents.length
    ? analysis.referenced_memory_incidents
    : memoryMatches.slice(0, 3).map((match) => ({
        id: match.matched_incident_id ?? match.id,
        title: match.title ?? match.metadata?.title ?? "Memory incident",
        vendor: match.vendor ?? match.metadata?.vendor ?? "unknown",
        similarity: match.similarity ?? 0,
      }))

  return (
    <div className="mb-2 w-full overflow-hidden rounded-xl border border-gray-100 bg-white shadow-sm">
      <div className="border-b border-gray-100 bg-[#FAFAFA] px-5 py-4">
        <p className="text-[12px] font-bold uppercase tracking-[0.14em] text-teal-700">
          Incident Intelligence Report
        </p>
        <p className="mt-2 text-[18px] font-semibold leading-7 text-gray-950">
          {analysis.diagnosis}
        </p>
      </div>

      <div className="space-y-4 px-5 py-5">
        <ReportSection icon={Brain} title="Most likely cause">
          {analysis.likely_cause}
        </ReportSection>

        <ReportSection icon={Target} title="Recommended response">
          {analysis.recommended_next_actions[0] ?? "Collect vendor status, dependency latency, and recent deploy evidence before mitigation."}
        </ReportSection>

        {analysis.checks_to_skip.length > 0 && (
          <ReportSection icon={ShieldAlert} title="Checks to avoid">
            <ul className="space-y-1">
              {analysis.checks_to_skip.slice(0, 4).map((check) => (
                <li key={check}>- {check}</li>
              ))}
            </ul>
          </ReportSection>
        )}

        <div className="grid grid-cols-2 gap-2">
          <div className="rounded-lg border border-gray-100 bg-gray-50 p-4">
            <div className="mb-1 flex items-center gap-1.5 text-[12px] font-bold uppercase tracking-[0.1em] text-gray-500">
              <BadgeCheck className="h-3 w-3" />
              Evidence strength
            </div>
            <p className="text-[18px] font-bold text-gray-950">
              {typeof evidenceStrength === "number" ? formatEvidenceStrength(evidenceStrength) : "Measured"}
            </p>
          </div>
          <div className="rounded-lg border border-gray-100 bg-gray-50 p-4">
            <div className="mb-1 flex items-center gap-1.5 text-[12px] font-bold uppercase tracking-[0.1em] text-gray-500">
              <Activity className="h-3 w-3" />
              Uncertainty
            </div>
            <p className="line-clamp-3 text-[14px] leading-6 text-gray-600">
              {analysis.uncertainty_note}
            </p>
          </div>
        </div>

        <ReportSection icon={FileDown} title="Evidence used / memory sources">
          <div className="space-y-1.5">
            {evidence.slice(0, 4).map((ref) => (
              <div key={ref.id} className="rounded-md border border-gray-100 bg-gray-50 px-3 py-2">
                <p className="truncate text-[13px] font-semibold text-gray-900">{ref.title}</p>
                <p className="text-[12px] leading-5 text-gray-500">
                  {ref.vendor} · {formatEvidenceStrength(ref.similarity)} evidence
                </p>
              </div>
            ))}
          </div>
        </ReportSection>
      </div>
    </div>
  )
}

function formatEvidenceStrength(similarity: number) {
  if (similarity >= 0.82) return "strong"
  if (similarity >= 0.58) return "moderate"
  return "weak"
}

function ReportSection({
  icon: Icon,
  title,
  children,
}: {
  icon: typeof Brain
  title: string
  children: ReactNode
}) {
  return (
    <section className="rounded-lg border border-gray-100 bg-white p-4">
      <div className="mb-2 flex items-center gap-2">
        <Icon className="h-3.5 w-3.5 text-teal-700" />
        <p className="text-[12px] font-bold uppercase tracking-[0.1em] text-gray-500">
          {title}
        </p>
      </div>
      <div className="text-[15px] leading-7 text-gray-700">{children}</div>
    </section>
  )
}
